preprefinal/cart/urls.py
from django.conf.urls import url
from . import views

app_name = "cart"


urlpatterns = [
    url(r"^$", views.cart_detail, name="cart_detail"),
    url(r"^add/(?P<product_id>\d+)/$", views.cart_add, name="cart_add"),
    url(r"^remove/(?P<product_id>\d+)$", views.cart_remove, name="cart_remove"),
]

preprefinal/fullstack_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("shop/", include("shop.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

preprefinal/shop/urls.py
from django.conf.urls import url
from . import views

app_name = "shop"

urlpatterns = [
    url(r"^$", views.product_list, name="product_list"),
    url(
        r"^(?P<category_slug>[-\w]+)/$",
        views.product_list,
        name="product_list_by_category",
    ),
    url(
        r"^(?P<id>\d+)/(?P<slug>[-\w]+)/$", views.product_detail, name="product_detail"
    ),
]

preprefinal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        
        <meta charset="utf-8">
        
        <title>Online demo site</title>

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Marck+Script&amp;subset=cyrillic" rel="stylesheet">

        <link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon/favicon-16x16.png">
        <link rel="manifest" href="/static/images/favicon/site.webmanifest">
        <link rel="mask-icon" href="/static/images/favicon/safari-pinned-tab.svg" color="#334d66">
        <link rel="shortcut icon" href="/static/images/favicon/favicon.ico">
        <meta name="msapplication-TileColor" content="#f9f6f4">
        <meta name="msapplication-config" content="/static/images/favicon/browserconfig.xml">
        <meta name="theme-color" content="#f9f6f4">

         </head>
    <style>
    
      body {
        font-size: 1.2rem;
      }
      nav {
        font-size: 1rem;
      }
      .navbar-brand {
        padding-top: 0;
      }
    </style>
    <body>
        <!-- -->
        <nav class="bg-dotted-red sticky-top">
          <nav class="container navbar navbar-expand-lg">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="/static/images/logo.png" alt="Online Demo Site" class="logo"></a>
            <div class="nav-item d-lg-none">
              <a class="nav-link" href="tel:+77079641114"><i class="fas fa-phone-square"></i></a>
            </div>
            <div class="nav-item d-lg-none">
              <a class="nav-link" href="https://wa.me/77079641114?text=I'm%20interested%20in%20your%20car%20for%20sale"><i class="fab fa-whatsapp-square"></i> WhatsApp</a>
            </div>
            <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Delivery</a>
                </li>
                </ul>
              {% if user.is_authenticated %}
                <div class="nav-item">
                  <a class="nav-link" href="#"><i class="fas fa-user"></i> {{ user.username }}</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a>
                </div>
              {% else %} 
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> To come in</a>
                </div>
              {% endif %}
              <div class="nav-item">                
                  {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                      <a class="nav-link text-red" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-bag"></i> {{ total_items }}</a>
                    {% else %}
                      <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-bag"></i></a>
                    {% endif %}
                  {% endwith %}
              </div>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="To find" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
              </form>
            </div>
          </nav>
        </nav>
        <main class="">
            {% block intro %}
            {% endblock intro %}
            
            {% block top-level-category %}
            {% endblock top-level-category %}

            {% block shop_now %}
            {% endblock shop_now %}

            {% block brands %}
            {% endblock brands %}
              
          
            <section>
                <div class="container py-1 my-3" >
                    {% block content %}
                    {% endblock %}
                </div>
            </section>
          

          {% block product-list %}
            
          {% endblock product-list %}
          
            

            </main>
        <!-- -->

        <!-- -->
        <footer class="small bg-black">
            <div class="container">
                <div class="row py-4">
                    <div class="col-md-4">
                        <h5>About company</h5>
                        <p><a href="{% url 'home' %}" class="san">Saikiran</a>- Online Demoo Site</p>
                       </div>
                </div>

                <div class="row">
                    <div class="nav-item"><a href="{% url 'home' %}" class="nav-link">2020 © <span class="san">Sai Kiran</span></a></div>
                 </div>
                <a class="text-whsm" href="#"><div class="btn btn-block pb-4"><i class="fas fa-chevron-up pb-4"></i></div></a>
            </div>
        </footer>
       


        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

preprefinal/templates/home.html
{% extends 'base.html' %}

{% block intro %}
    <section id="intro" class="bg-dotted-red">
        <div class="container jumbotron text-center my-0">
            <h1 class="display-4 san-big">Online Demo Site</h1>
            <p>Online store tights</p>
        </div>
    </section>
{% endblock intro %}

{% block top-level-category %}
    <section id="top-level-category" class="bg-dotted-red">
        <nav class="container">
          <ul class="nav justify-content-center">
              <li class="nav-item">
                <a class="nav-link" href="#!">Classic</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#!">PartyWears</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#!">Shoes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#!">Jeans</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#!">Sarees</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#!">Watches</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#!">Sandals</a>
              </li>
          </ul>
        </nav>
    </section>
{% endblock top-level-category %}

{% block shop_now %}
    <section>
        <div class="container my-4 py-4 text-center">
            <h3 class="san-big text-red"><a href="/shop">Buy now</a></h3>
        </div>
    </section>
{% endblock shop_now %}

{% block brands %}
    <section id="brands" >
        <div class="container">
            <div class="my-3">
                <h2>Our favorite brands</h2>
            </div>
            
            <div class="card-columns">
                <div class="card brand-card">
                    <a href="#">
                        <img class="card-img " src="/static/images/denim.jpeg" alt="Card image">
                        <div class="card-img-overlay">
                            <h2 class="brand-card-text">DENIM</h2>
                        </div>
                    </a>
                </div>
                <div class="card brand-card">
                    <a href="#">
                        <img class="card-img " src="/static/images/puma.png" alt="Card image">
                        <div class="card-img-overlay">
                            <h2 class="brand-card-text">PUMA</h2>
                        </div>
                    </a>
                </div>
                <div class="card brand-card">
                    <a href="#">
                        <img class="card-img " src="/static/images/levis.jpg" alt="Card image">
                        <div class="card-img-overlay">
                            <h2 class="brand-card-text">LEVIS</h2>
                        </div>
                    </a>
                </div>
                <div class="card brand-card">
                    <a href="#">
                        <img class="card-img " src="/static/images/tommy.png" alt="Card image">
                        <div class="card-img-overlay">
                            <h2 class="brand-card-text">TOMMY</h2>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
{% endblock brands %}

{% block content %}
    {% for post in object_list %}
        <div class="post-entry">
            <h2><a href="">{{ post.title }}</a></h2>
            <p>{{ post.body }}</p>
        </div>
    {% endfor %}
{% endblock content %}

{% block product-list %}
<section id="" class="my-3">
    <div class="container">
        
        <div class="row">
            {% for product in products %}
                <div class="col-6 col-sm-6 col-md-4 col-lg-3">
                    <div class="card ">
                        <div class="card-body">
                            
                            <div class="product-image small">
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="card-img-top"
                                         src="
                                            {% if product.image %}
                                                {{ product.image.url }} 
                                            {% else %}
                                                /static/images/product-image.jpg
                                            {% endif %}
                                            " alt="{{ product.name }}
                                            ">
                                </a>
                            </div>

                            <div class="product-brand small mt-1">Levante</div>

                            <div class="product-name font-weight-bold">
                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </div>

                            <div class="product-price">₹{{ product.price }}</div>
                            <div class="product-size text-monospace">S M L XL XXL</div>
                            <div class="product-color d-flex justify-content-start small text-center">
                                <div class="product-color-item bg-primary rounded-circle">B</div>
                                <div class="product-color-item bg-info rounded-circle">I</div>
                                <div class="product-color-item bg-danger rounded-circle">R</div>
                            </div>
                            <div class="product-promo small font-italic text-red">Buy 3 - get 15% discount!</div>
                            <div class="btn-group mt-1">
                                <button class="btn bg-red text-white">0</button>
                                <button class="btn bg-black text-whsm">Buy</button>
                            </div>
                            
                        </div>
                    </div>
                </div>
            {% endfor %}            
        </div>
        <hr/>
    </div>
</section>
{% endblock product-list %}

preprefinal/templates/post_delete.html
{% extends "base.html" %}


{% block content %}
    <h1>Delete post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <a href="{% url 'post_detail' post.pk %}"><button type="button">Cancel</button></a><input type="submit" value="Confirm" />
    </form>
{% endblock content %}

preprefinal/templates/post_detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
    </div>

    <p><a href="{% url 'post_edit' post.pk %}">+ Edit Post</a></p>
    <p><a href="{% url 'post_delete' post.pk %}">+ Delete Post</a></p>
{% endblock content %}

preprefinal/templates/post_edit.html
{% extends "base.html" %}


{% block content %}
    <h1>Edit post</h1>
    <form action="" method="post"> {% csrf_token %} 
        {{ form.as_p }}
        <input type="submit" value="Update" />

    </form>
  
{% endblock content %}

preprefinal/templates/post_new.html
{% extends 'base.html' %}


{% block content %}
    <div>
        <h1>New Post</h1>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="save" />
        </form>

    </div>
{% endblock content%}

preprefinal/templates/product_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div id="image" class="col-md-6">
        <img class="card-img-top" alt="{{ product.name }}" 
        src="
            {% if product.image %}
                {{ product.image.url }} 
            {% else %}
                /static/images/product-image.jpg
            {% endif %}
        ">
    </div>
    <div id="info" class="col-md-6">
        <h3>{{ product.name }}</h3>
        <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>

        <div class="product-brand small mt-1">Levante</div>

        <div class="product-price">₹{{ product.price }}</div>

        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                {% csrf_token %}
                {{ cart_product_form }}
                <input type="submit" value="Add to Cart" class="btn btn-primary">
        </form>

        <div class="product-description"><p>{{ product.description|safe|linebreaksbr }}</p></div>
    </div>
  </div>
{% endblock content %}

preprefinal/templates/product_list.html
{% extends "base.html" %}

{% block top-level-category %}
    <section id="top-level-category" class="bg-dotted-red">
        <nav class="container">
          <ul class="nav justify-content-center">

              <li 
                {% if not category %}
                    class="nav-item font-weight-bold"
                {% endif %}>
                <a class="nav-link" href="{% url 'shop:product_list' %}">All</a>
              </li>

              {% for c in categories %}


              <li 
                {% if category.slug == c.slug %}
                    class="nav-item font-weight-bold"
                {% endif %}>
                <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>

              {% endfor %}
              
          </ul>
        </nav>
    </section>
{% endblock top-level-category %}

{% block product-list %}
<section id="" class="my-3">
    <div class="container">
        
        <div class="row">
            {% for product in products %}
                <div class="col-6 col-sm-6 col-md-4 col-lg-3">
                    <div class="card ">
                        <div class="card-body">
                            
                            <div class="product-image small">
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="card-img-top"
                                         src="
                                            {% if product.image %}
                                                {{ product.image.url }} 
                                            {% else %}
                                                /static/images/product-image.jpg
                                            {% endif %}
                                            " alt="{{ product.name }}
                                            ">
                                </a>
                            </div>

                            <div class="product-brand small mt-1">Levante</div>

                            <div class="product-name font-weight-bold">
                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </div>

                            <div class="product-price"><p>₹{{ product.price }}</p></div>
                            <div class="product-size text-monospace">S M L XL XXL</div>
                            <div class="product-color d-flex justify-content-start small text-center">
                                <div class="product-color-item bg-primary rounded-circle">B</div>
                                <div class="product-color-item bg-info rounded-circle">I</div>
                                <div class="product-color-item bg-danger rounded-circle">R</div>
                            </div>
                            <div class="product-promo small font-italic text-red">Buy 3 - get 15% discount!</div>
                            <div class="btn-group mt-1">
                                <button class="btn bg-red text-white">0</button>
                                <button class="btn bg-black text-whsm">Buy</button>
                            </div>
                            
                        </div>
                    </div>
                </div>
            {% endfor %}            
        </div>
        <hr/>
    </div>
</section>

{% endblock product-list %}

preprefinal/templates/signup.html
{% extends "base.html" %}

{% block content %}
    <h2>Sign Up</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock content %}